apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DB_USER: {{ .Values.mysql.auth.username }}
  DB_NAME: {{ .Values.mysql.auth.database }}
  DB_HOST: {{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local