apiVersion: v1
kind: Service
metadata:
  name: {{ include "otusapp-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otusapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: web
  selector:
    {{- include "otusapp-chart.selectorLabels" . | nindent 4 }}