{
 "title": "OTUS app",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", pod=~\"^otusapp.+\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^otusapp-.+\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "App latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(http_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(http_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(http_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(Inf, sum by (le)(rate(http_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "+inf"
    }
   ]
  },
  {
   "title": "Nginx latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(Inf, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "+inf"
    }
   ]
  },
  {
   "title": "App RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_nginx_process_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "App Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{status=\"5xx\"}[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (status) (irate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}