# Default values for otusapp_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dismay/otusapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

mysql:
  enabled: true
  auth:
    rootPassword: "mysql_password"
    database: otus_db
    username: "mysql_user"
    password: "mysql_password"
  primary:
    persistence:
      enabled: false
