apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-ing
  namespace: otus
  annotations:
    kubernates.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - backend:
              service:
                name: otus-srv
                port:
                  number: 8000
            pathType: Exact
            path: /health
          - backend:
              service:
                name: otus-srv
                port:
                  number: 8000
            path: /otusapp/(\w+)/(\w+)$
            pathType: Exact