{{- $svcPort := .Values.service.port -}}
{{- $appName := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - backend:
              service:
                name: {{ $appName }}-srv
                port:
                  number: {{ $svcPort }}
            pathType: {{ .pathType }}
            path: {{ .path }}
          {{- end }}
    {{- end }}